[package]
name = "planeshift"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
edition = "2018"

[features]
default = ["enable-winit"]
enable-glx = ["gl_generator", "x11"]
enable-glx-default = ["enable-glx"]
enable-winit = ["winit"]

[build-dependencies.gl_generator]
version = "0.9"
optional = true

[target.'cfg(target_os = "linux")'.build-dependencies]
gl_generator = "0.9"

[dependencies]
euclid = "0.19"
gleam = "0.6"

[dependencies.winit]
version = "0.17"
optional = true

[dependencies.x11]
version = "2.18"
optional = true

[target.'cfg(target_os = "linux")'.dependencies]
x11 = "2.18"

[target.'cfg(target_os = "macos")'.dependencies]
cgl = "0.2"
objc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies.cocoa]
path = "/Users/pcwalton/Source/core-foundation-rs/cocoa"

[target.'cfg(target_os = "macos")'.dependencies.core-foundation]
path = "/Users/pcwalton/Source/core-foundation-rs/core-foundation"

[target.'cfg(target_os = "macos")'.dependencies.core-graphics]
path = "/Users/pcwalton/Source/core-foundation-rs/core-graphics"

[target.'cfg(target_os = "macos")'.dependencies.io-surface]
path = "/Users/pcwalton/Source/core-foundation-rs/io-surface"

[dev-dependencies]
image = "0.20"
offscreen_gl_context = "0.21"
winit = "0.17"
